---
apiVersion: v1
kind: Pod
metadata:
  name: mongorestore-widget
  namespace: mongodb
spec:
  containers:
    - name: app
      image: ghcr.io/kyoobit/mongorestore-widget:latest
      env:
        - name: MONGO_RW_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-readwrite
              key: username
        - name: MONGO_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-readwrite
              key: password
        - name: ENCRYPTION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-encryption
              key: password
        - name: OSS
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: oss
        - name: OSS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: oss_bucket
        - name: OSS_PATH
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: oss_path
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: mongo_db
        - name: MONGO_COL
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: mongo_col
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: cloudflare-r2-dumps
              key: mongo_uri
      volumeMounts:
        - name: rclone-config
          mountPath: "/etc/rclone"
          readOnly: true
  volumes:
    - name: rclone-config
      secret:
        secretName: cloudflare-r2-ro
        #optional: true
